apiVersion: apps/v1
kind: Deployment
metadata:
   name: catalogue
   labels:
      app: nodejs
      project: roboshop
      service: catalogue
      env: dev
spec:
   replicas: 1
   selector:
      matchLabels:
         app: nodejs
         project: roboshop
         service: catalogue
         env: dev
   template:
      metadata:
         labels:
            app: nodejs
            project: roboshop
            service: catalogue
            env: dev
      spec:
         serviceAccountName: catalogue
         containers:
            - name: catalogue
              image: hemanthtadikonda/catalogue:1.1.0
              ports:
                 - containerPort: 8080
              envFrom:
                 -  configMapRef:
                       name: catalogue-config
              resources:
                 requests:
                    memory: "500Mi"
                    cpu: "250m"
                 limits:
                    memory: "500Mi"
                    cpu: "250m"
              livenessProbe:
                 httpGet:
                    path: /health
                    port: 8080
                 initialDelaySeconds: 10
                 periodSeconds: 5
              readinessProbe:
                 httpGet:
                    path: /health
                    port: 8080
                 initialDelaySeconds: 10
                 periodSeconds: 5
---
apiVersion: v1
kind: ServiceAccount
metadata:
   name: catalogue
---
apiVersion: v1
kind: Service
metadata:
   name: catalogue
spec:
   selector:
      app: nodejs
      project: roboshop
      service: catalogue
      env: dev
   ports:
      - protocol: TCP
        port: 8080
        targetPort: 8080
---
apiVersion: v1
kind: ConfigMap
metadata:
   name: catalogue-config
data:
   MONGO_URL: "mongodb://mongodb:27017/catalogue"